# Generated by Django 3.2.18 on 2023-04-24 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kolo', '0002_auto_20230424_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mail_adress',
            new_name='mail_address',
        ),
        migrations.AddField(
            model_name='student',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
